### ISSUE TITLE
MaxEnt model&Arcgis

### ISSUE THREAD

**Issue by HU0920** [marinebon/sdm-explore#2]
I have run 114 species under 1 family using the Maxent model, what do I need to do in Arcgis that will enable me to know the range of distribution of the family's fitness zones.

**Comment by bbest** [comment]
Hi @HU0920,

I'm not sure. You might assign a threshold with ROC to each to convert to binary, then add all layers in the stack to come up with an overall range. 

I'm mostly using R (and some Python) and avoiding commercial packages for the sake of accesssibility and reproducibility. If you would like to continue using ArcGIS, I recommend checking out this package:

* [Marine Geospatial Ecology Tools](https://mgel.env.duke.edu/mget/)

Are you working on marine species? How did you come across this repository? I just started this online book on MarineSDMs for which we welcome contributions:

* [marinebon.github.io/MarineSDMs](https://marinebon.github.io/MarineSDMs/)

Cheers, Ben

**Comment by HU0920** [comment]
Hi. @bbest 
Thank you very much for your advice, I'm working on land animals. But I have relevant databases for understanding marine species, https://obis.org/, this is a site you can look at.
